homepage: "https://mosquitto.org/"
language: c
primary_contact: "roger@atchoo.org"
auto_ccs:
 - "security@eclipse.org"
 - "rogerlight@gmail.com"
sanitizers:
 - address
main_repo: 'git@github.com:Team-Atlanta/cp-c-mosquitto-src.git'

fuzzing_engines:
  - libfuzzer
