# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --preview
          - --enable-unstable-feature
          - string_processing

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=88]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --ignore=E203,W503,E226

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language: python
        additional_dependencies:
          - "redis"
          - "types-PyYAML"
          - "types-python-dateutil"
          - "types-requests"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks

  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7  # Use the latest stable version
  #   hooks:
  #     - id: actionlint
  #       files: ^\.github/workflows/.*\.ya?ml$

  # - repo: local
  #   hooks:
  #     - id: pre-push-results-check
  #       name: Check results folder and push to result repo before push
  #       entry: hooks/pre-push-check.sh
  #       language: script
  #       stages: [pre-push]
  #       verbose: true

exclude: "results/.*"
