version: '3.8'

services:
  crs-sarif:
    build:
      context: .
      dockerfile: Dockerfile
    image: crs-sarif:latest
    ports:
      - "${CRS_SARIF_PORT:-4321}:80"
    container_name: crs-sarif-${PROJECT_NAME}
    environment:
      LITELLM_KEY: ${LITELLM_KEY}
      VAPI_HOST: ${VAPI_HOST}
      CRS_TARGET: ${CRS_TARGET}
      CRS_SARIF_REDIS_URL: ${CRS_SARIF_REDIS_URL}
      CRS_MODE: ${CRS_MODE}
      BUILD_DIR: ${BUILD_DIR}
      OUT_DIR: ${OUT_DIR}
      SRC_DIR: ${SRC_DIR}
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_LANGUAGE: ${PROJECT_LANGUAGE}
      TARBALL_DIR: ${TARBALL_DIR}
      MULTILANG_BUILD_DIR: ${MULTILANG_BUILD_DIR}
      BUILD_SHARED_DIR: ${BUILD_SHARED_DIR}
      COVERAGE_SHARED_DIR: ${COVERAGE_SHARED_DIR}
      CORPUS_SHARED_DIR: ${CORPUS_SHARED_DIR}
      REACHABILITY_SHARED_DIR: ${REACHABILITY_SHARED_DIR}
      CALL_TRACE_SHARED_DIR: ${CALL_TRACE_SHARED_DIR}
      COVERAGE_REQUEST_SHARED_DIR: ${COVERAGE_REQUEST_SHARED_DIR}
      ORIGINAL_SARIF_SHARED_DIR: ${ORIGINAL_SARIF_SHARED_DIR}
      JAVA_CP_METADATA_PATH: ${JAVA_CP_METADATA_PATH}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      SANITIZER: ${SANITIZER}
      FUZZING_ENGINE: ${FUZZING_ENGINE}
      HELPER: ${HELPER}
      FUZZING_LANGUAGE: ${FUZZING_LANGUAGE}
      POCGEN_ROOT_DIR: ${POCGEN_ROOT_DIR}
      POCGEN_JOERN_DIR: ${POCGEN_JOERN_DIR}
      POCGEN_OUTPUT_DIR: ${POCGEN_OUTPUT_DIR}
      POCGEN_WORK_DIR: ${POCGEN_WORK_DIR}
      POCGEN_CP_NAME: ${POCGEN_CP_NAME}
      POCGEN_REPO_SRC_PATH: ${POCGEN_REPO_SRC_PATH}
      POCGEN_DEBUG_SRC_DIR: ${POCGEN_DEBUG_SRC_DIR}
      POCGEN_DEBUG_BIN_DIR: ${POCGEN_DEBUG_BIN_DIR}
      POCGEN_SHARED_DIR: ${POCGEN_SHARED_DIR}
      BUILDER_OUT_DIR: ${BUILDER_OUT_DIR}
    privileged: true
    volumes:
      - ${CRS_SARIF_HOST_VOLUME}:${CRS_SARIF_DOCKER_VOLUME}
    depends_on:
      - redis
    networks:
      - crs-network
    # command: ["tail", "-f", "/dev/null"]

  redis:
    image: redis:latest
    container_name: crs-redis-${PROJECT_NAME}
    volumes:
      - type: tmpfs
        target: /data
    networks:
      - crs-network

networks:
  crs-network:
    driver: bridge