codecov:
  max_report_age: off
ignore:
  - "deps/picohttpparser"
  - "deps/*.h"
  - "plugins/examples"
  - "test"
  - "^.*/test/.*"
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
