[project]
name = "python-oss-fuzz-vulnerability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.11.7", "python-oss-fuzz"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["oss_fuzz_vulnerability"]

[tool.uv.sources]
python-oss-fuzz = { workspace = true }
