[package]
name = "concolic_executor"
version = "0.13.2"
edition = "2021"

[lib]
name = "concolic_executor"
path = "src/lib.rs"
crate-type = ["staticlib"]

[features]
default = []
legacy_format = []

[profile.dev]
lto = false
opt-levl = 0
debug = true

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
panic = "abort"

[dependencies]
libafl = { path = "../LibAFL/libafl/", features = ["concolic_mutation"] }
clap = { version = "4.0", features = ["derive"] }
mimalloc = { version = "*", default-features = false }
libc = "0.2.158"
symcc_runtime = { path = "../LibAFL/libafl_concolic/symcc_runtime", features = ["debug_concolic_tracing_runtime"] }
anyhow = { version = "1.0.86", features = ["backtrace"] }
ctor = "0.2.8"
serde_json = "1.0.132"
once_cell = "1.20.2"
serde = "1.0.215"
serde_cbor = "0.11.2"
backtrace = "0.3.74"
postcard = { version = "1.1.1", features = ["use-std"] }
rand = "0.9.1"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1"
which = "4.4"
symcc_libafl = { path = "../LibAFL/libafl_concolic/symcc_libafl" }

[workspace]

