---
apiVersion: v1
kind: Service
metadata:
  name: crs-webapp
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: crs-webapp

---
apiVersion: v1
kind: Service
metadata:
  name: p3
  namespace: crs-webservice
  labels:
    app: p3
spec:
  type: ClusterIP
  selector:
    app: p3
  ports:
    - name: p3-8000
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: p3-8001
      port: 8001
      targetPort: 8001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otel
  namespace: crs-webservice
spec:
  selector:
    app: otel
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
